PRAGMA foreign_keys=OFF;
CREATE TABLE users (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,email text NOT NULL,display_name text NOT NULL,status text DEFAULT 'ACTIVE' NOT NULL,locale text DEFAULT 'pt-BR' NOT NULL,last_login_at text,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX uq_users_email ON users(email);
CREATE TABLE auth_identities (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,user_id integer NOT NULL REFERENCES users(id),provider text NOT NULL,provider_subject text NOT NULL,email_verified_at text,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX uq_auth_provider_subject ON auth_identities(provider,provider_subject);
CREATE TABLE workspaces (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,name text NOT NULL,base_currency text DEFAULT 'BRL' NOT NULL,timezone text DEFAULT 'America/Sao_Paulo' NOT NULL,fx_mode text DEFAULT 'PTAX_WITH_MANUAL_OVERRIDE' NOT NULL,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
INSERT INTO workspaces (id,name) VALUES (1,'Carteira fundadora');
CREATE TABLE workspace_members (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),user_id integer NOT NULL REFERENCES users(id),role text DEFAULT 'WORKSPACE_OWNER' NOT NULL,status text DEFAULT 'ACTIVE' NOT NULL,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX uq_workspace_member ON workspace_members(workspace_id,user_id);
CREATE INDEX idx_workspace_members_user ON workspace_members(user_id);
CREATE TABLE consents (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),user_id integer NOT NULL REFERENCES users(id),purpose text NOT NULL,legal_basis text DEFAULT 'CONSENT' NOT NULL,version text NOT NULL,status text DEFAULT 'GRANTED' NOT NULL,granted_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,revoked_at text,evidence_json text DEFAULT '{}' NOT NULL);
CREATE TABLE audit_logs (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer,user_id integer,action text NOT NULL,entity_type text NOT NULL,entity_id text,metadata_json text DEFAULT '{}' NOT NULL,ip_hash text,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX idx_audit_workspace_created ON audit_logs(workspace_id,created_at);
CREATE TABLE portfolios (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),name text DEFAULT 'Carteira principal' NOT NULL,base_currency text DEFAULT 'BRL' NOT NULL,status text DEFAULT 'ACTIVE' NOT NULL,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
DROP INDEX IF EXISTS uq_import_batches_content_hash;
ALTER TABLE import_batches ADD COLUMN workspace_id integer NOT NULL DEFAULT 1 REFERENCES workspaces(id);
ALTER TABLE import_batches ADD COLUMN fx_source text NOT NULL DEFAULT 'MANUAL';
ALTER TABLE import_batches ADD COLUMN fx_reference_date text;
ALTER TABLE import_batches ADD COLUMN rolled_back_at text;
CREATE UNIQUE INDEX uq_import_batches_workspace_hash ON import_batches(workspace_id,content_hash);
CREATE INDEX idx_import_batches_workspace_created ON import_batches(workspace_id,created_at);
ALTER TABLE positions ADD COLUMN workspace_id integer NOT NULL DEFAULT 1 REFERENCES workspaces(id);
ALTER TABLE positions ADD COLUMN currency text NOT NULL DEFAULT 'BRL';
CREATE INDEX idx_positions_workspace_batch ON positions(workspace_id,import_batch_id);
CREATE TABLE portfolio_snapshots (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),import_batch_id integer REFERENCES import_batches(id),as_of text NOT NULL,total_brl real NOT NULL,total_usd real NOT NULL,fx_usd_brl real NOT NULL,quality text DEFAULT 'CURRENT_POSITION_ONLY' NOT NULL,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX uq_snapshot_workspace_batch ON portfolio_snapshots(workspace_id,import_batch_id);
CREATE TABLE incomes (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),type text NOT NULL,ticker text,asset_name text NOT NULL,amount real NOT NULL,currency text DEFAULT 'BRL' NOT NULL,payment_date text NOT NULL,source text DEFAULT 'MANUAL' NOT NULL,notes text,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX idx_incomes_workspace_date ON incomes(workspace_id,payment_date);
CREATE TABLE investment_theses (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),ticker text,asset_name text NOT NULL,objective text NOT NULL,horizon text NOT NULL,buy_reason text NOT NULL,increase_criteria text NOT NULL,reduce_criteria text NOT NULL,exit_criteria text NOT NULL,main_risk text NOT NULL,status text DEFAULT 'ACTIVE' NOT NULL,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,updated_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE concentration_rules (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),dimension text NOT NULL,threshold_percent real NOT NULL,enabled integer DEFAULT 1 NOT NULL,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE UNIQUE INDEX uq_concentration_workspace_dimension ON concentration_rules(workspace_id,dimension);
CREATE TABLE fx_rates (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,pair text DEFAULT 'USD/BRL' NOT NULL,rate real NOT NULL,source text NOT NULL,reference_date text NOT NULL,fetched_at text DEFAULT CURRENT_TIMESTAMP NOT NULL,raw_json text NOT NULL);
CREATE UNIQUE INDEX uq_fx_pair_source_date ON fx_rates(pair,source,reference_date);
CREATE TABLE report_deliveries (id integer PRIMARY KEY AUTOINCREMENT NOT NULL,workspace_id integer NOT NULL REFERENCES workspaces(id),user_id integer NOT NULL REFERENCES users(id),format text NOT NULL,channel text NOT NULL,recipient text,status text NOT NULL,provider text,provider_message_id text,created_at text DEFAULT CURRENT_TIMESTAMP NOT NULL);
PRAGMA foreign_keys=ON;
