"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from "recharts";
import { Bell, Bot, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDollarSign, FileSpreadsheet, Gauge, Home, Menu, PieChart as PieIcon, Plus, Send, Settings, ShieldCheck, Sparkles, Upload, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";

type Position = { id: number; assetName: string; ticker: string | null; institution: string; assetClass: string; quantity: number; marketValueBrl: number; confidence: number };
type Summary = { empty: boolean; totalBrl: number; totalUsd: number; fxUsdBrl?: number; institutions: number; allocation: { name: string; value: number }[]; positions: Position[]; batch?: { fileName: string; createdAt: string; rowCount: number; rejectedCount: number } };
const colors = ["#0d6b5d", "#47a993", "#ff8f70", "#6672a8", "#d7d0cb", "#ffb000"];
const money = (value: number, currency: "BRL" | "USD") => new Intl.NumberFormat("pt-BR", { style: "currency", currency, maximumFractionDigits: 2 }).format(value);

function Logo() { return <div className="brand"><span className="brand-mark"><i /><i /><i /></span><span>Evidaris</span></div>; }
const menu = [[Home,"Visão geral"],[WalletCards,"Minha carteira"],[Upload,"Importações"],[Gauge,"Performance"],[CircleDollarSign,"Rendimentos"],[PieIcon,"Concentração"],[ShieldCheck,"Minha tese"],[FileSpreadsheet,"Relatórios"],[Settings,"Configurações"]] as const;

function AllocationLegend({ data, total, currency, fx }: { data: Summary["allocation"]; total: number; currency: "BRL" | "USD"; fx: number }) {
  return <div className="allocation-list">{data.map((item,index)=><div className="allocation-row" key={item.name}><span className="dot" style={{background:colors[index%colors.length]}}/><span>{item.name}</span><strong>{total?Math.round(item.value/total*100):0}%</strong><em>{money(currency==="BRL"?item.value:item.value/fx,currency)}</em></div>)}</div>;
}

export default function Dashboard() {
  const [summary,setSummary]=useState<Summary>({empty:true,totalBrl:0,totalUsd:0,institutions:0,allocation:[],positions:[]});
  const [currency,setCurrency]=useState<"BRL"|"USD">("BRL"); const [importOpen,setImportOpen]=useState(false); const [aiOpen,setAiOpen]=useState(false);
  const [file,setFile]=useState<File|null>(null); const [fxRate,setFxRate]=useState("5,42"); const [loading,setLoading]=useState(false); const [notice,setNotice]=useState(""); const inputRef=useRef<HTMLInputElement>(null);
  useEffect(()=>{fetch("/api/portfolio").then(r=>r.ok?r.json():null).then(data=>data&&setSummary(data)).catch(()=>null)},[]);
  const fx=summary.fxUsdBrl||5.42; const shownTotal=currency==="BRL"?summary.totalBrl:summary.totalUsd;
  const chartData=useMemo(()=>{const total=shownTotal||100000;return [0.71,0.75,0.74,0.81,0.84,0.87,0.85,0.91,0.89,0.94,0.97,1].map((factor,index)=>({month:["Set","Out","Nov","Dez","Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago"][index],value:total*factor}))},[shownTotal]);

  async function importFile(selected=file){if(!selected)return;setLoading(true);setNotice("");const form=new FormData();form.append("file",selected);form.append("fxUsdBrl",fxRate.replace(",","."));try{const response=await fetch("/api/portfolio",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"Não foi possível importar o arquivo.");setSummary(result);setNotice(result.duplicate?"Esse arquivo já havia sido importado. Nenhuma posição foi duplicada.":`${result.batch.rowCount} posições importadas com sucesso.`);setFile(null)}catch(error){setNotice(error instanceof Error?error.message:"Falha ao importar")}finally{setLoading(false)}}
  function useExample(){const csv="Produto;Código de Negociação;Tipo de Produto;Instituição;Conta;Quantidade;Preço de Fechamento;Valor Atualizado\nPetrobras PN;PETR4;Ações;XP Investimentos;001;120;38,45;4614,00\nVanguard S&P 500 BDR;IVVB11;ETFs;BTG Pactual;002;42;366,70;15401,40\nFII Kinea Rendimentos;KNCR11;Fundo Imobiliário;XP Investimentos;001;85;103,25;8776,25\nTesouro IPCA+ 2035;;Tesouro Direto;Tesouro Direto;TD;1;5248,90;5248,90";const sample=new File([csv],"posicao-b3-exemplo.csv",{type:"text/csv"});setFile(sample);void importFile(sample)}

  return <main className="app-shell"><aside className="sidebar"><Logo/><nav>{menu.map(([Icon,label],index)=><button className={index===0?"active":""} key={label}><Icon/>{label}</button>)}</nav><div className="verified"><ShieldCheck/><strong>Carteira verificada</strong><span>{summary.empty?"Nenhum arquivo conciliado":`${summary.institutions} instituições · ${summary.positions.length} ativos`}</span><Progress value={summary.empty?0:100}/><small>{summary.empty?"Importe seu arquivo B3":"100% das posições lidas"}</small></div></aside>
  <section className="workspace"><header><button className="mobile-menu" aria-label="Abrir menu"><Menu/></button><div><h1>Bom dia, Guilherme <span>👋</span></h1><p>Aqui está o resumo da sua carteira</p></div><div className="header-actions"><select value={currency} onChange={e=>setCurrency(e.target.value as "BRL"|"USD")}><option>BRL</option><option>USD</option></select><button aria-label="Notificações"><Bell/></button><span className="avatar">GM</span></div></header>
  <div className="content-grid"><section className="hero-card"><div className="total-block"><span>Patrimônio total</span><strong>{money(shownTotal,currency)}</strong><small>≈ {money(currency==="BRL"?summary.totalUsd:summary.totalBrl,currency==="BRL"?"USD":"BRL")}</small><em>{summary.empty?"Aguardando a primeira importação":`Atualizado por ${summary.batch?.fileName}`}</em></div><div className="trend"><div className="trend-head"><span>Evolução do patrimônio ({currency})</span><div><b>1M</b><b>3M</b><b>6M</b><b className="selected">1A</b></div></div><ResponsiveContainer width="100%" height={170}><AreaChart data={chartData}><defs><linearGradient id="trend" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0d6b5d" stopOpacity={0.26}/><stop offset="1" stopColor="#0d6b5d" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{fill:"#7b8986",fontSize:11}}/><Tooltip formatter={value=>money(Number(value),currency)}/><Area type="monotone" dataKey="value" stroke="#0d6b5d" strokeWidth={2.5} fill="url(#trend)"/></AreaChart></ResponsiveContainer></div></section>
  <section className="import-card"><div className="import-icon"><FileSpreadsheet/></div><div><span>Conciliação B3</span><h2>{summary.empty?"Traga seu patrimônio":"Carteira atualizada"}</h2><p>{summary.empty?"Importe o Excel de posições da Área do Investidor.":`${summary.batch?.rowCount} linhas reconhecidas · ${summary.batch?.rejectedCount||0} pendências`}</p></div><Button onClick={()=>setImportOpen(true)}><Plus/>Importar arquivo</Button></section>
  <section className="result-card"><div className="section-title"><div><h2>Resultado real</h2><p>A decomposição de performance entra na próxima etapa</p></div><span className="status-pill">Base pronta</span></div><div className="metrics"><article><span>Valor de mercado</span><strong>{money(shownTotal,currency)}</strong><small>posição importada</small></article><article><span>Ativos</span><strong>{summary.positions.length}</strong><small>com evidência da B3</small></article><article><span>Instituições</span><strong>{summary.institutions}</strong><small>visão consolidada</small></article><article><span>Câmbio usado</span><strong>R$ {fx.toFixed(2)}</strong><small>USD/BRL editável</small></article></div></section>
  <section className="portfolio-card"><div className="section-title"><div><h2>Sua carteira</h2><p>Distribuição do patrimônio importado</p></div><button>Ver todos os ativos <ChevronRight/></button></div>{summary.empty?<div className="empty"><Upload/><h3>Nenhuma posição importada</h3><p>Você pode testar agora com um arquivo demonstrativo.</p><Button variant="outline" onClick={useExample}>Usar arquivo exemplo</Button></div>:<div className="portfolio-body"><div className="donut"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={summary.allocation} dataKey="value" innerRadius={62} outerRadius={92} paddingAngle={1}>{summary.allocation.map((item,index)=><Cell key={item.name} fill={colors[index%colors.length]}/>)}</Pie><Tooltip formatter={value=>money(currency==="BRL"?Number(value):Number(value)/fx,currency)}/></PieChart></ResponsiveContainer><div><strong>{money(shownTotal,currency)}</strong><span>Total</span></div></div><AllocationLegend data={summary.allocation} total={summary.totalBrl} currency={currency} fx={fx}/><div className="top-assets"><strong>Maiores posições</strong>{summary.positions.slice().sort((a,b)=>b.marketValueBrl-a.marketValueBrl).slice(0,3).map(position=><div key={position.id}><span>{position.ticker||position.assetName}</span><em>{money(currency==="BRL"?position.marketValueBrl:position.marketValueBrl/fx,currency)}</em></div>)}</div></div>}</section>
  <section className="insight"><Sparkles/><div><strong>Insight da sua carteira</strong><p>{summary.empty?"Importe sua posição para receber explicações rastreáveis sobre concentração, moeda e instituições.":`${summary.allocation[0]?.name||"Sua maior classe"} representa ${Math.round((summary.allocation[0]?.value||0)/summary.totalBrl*100)}% do patrimônio importado.`}</p></div><button onClick={()=>setAiOpen(true)}>Perguntar à IA <ChevronRight/></button></section></div></section>
  <button className="ai-fab" onClick={()=>setAiOpen(true)} aria-label="Abrir assistente Evidaris"><Bot/><span>Pergunte à Evidaris</span></button><nav className="mobile-nav"><button className="active"><Home/>Início</button><button><BriefcaseBusiness/>Carteira</button><button onClick={()=>setImportOpen(true)} className="import"><Plus/></button><button><FileSpreadsheet/>Relatórios</button><button onClick={()=>setAiOpen(true)}><Bot/>IA</button></nav>
  <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="import-dialog"><DialogHeader><DialogTitle>Importar posição da B3</DialogTitle><DialogDescription>Exporte o arquivo em Minhas Carteiras → Investimentos → Excel. Aceitamos XLSX, XLS e CSV.</DialogDescription></DialogHeader><div className="steps"><span className="done"><CheckCircle2/>Arquivo</span><i/><span>Validar</span><i/><span>Consolidar</span></div><button className="dropzone" onClick={()=>inputRef.current?.click()}><Upload/><strong>{file?file.name:"Arraste ou selecione seu arquivo"}</strong><span>O original ficará armazenado como evidência por 3 meses.</span></button><input ref={inputRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><label className="fx-field">Câmbio USD/BRL de referência<Input value={fxRate} onChange={e=>setFxRate(e.target.value)} inputMode="decimal"/></label>{notice&&<p className="notice">{notice}</p>}<div className="dialog-actions"><Button variant="outline" onClick={useExample}>Usar exemplo</Button><Button onClick={()=>void importFile()} disabled={!file||loading}>{loading?"Conciliando...":"Validar e importar"}</Button></div></DialogContent></Dialog>
  <Dialog open={aiOpen} onOpenChange={setAiOpen}><DialogContent className="ai-dialog"><DialogHeader><div className="ai-title"><span><Sparkles/></span><div><DialogTitle>Assistente Evidaris</DialogTitle><DialogDescription>Interface demonstrativa · respostas inteligentes entram na próxima etapa</DialogDescription></div></div></DialogHeader><div className="ai-welcome"><Bot/><div><strong>Como posso ajudar?</strong><p>Quando a IA estiver conectada, cada resposta mostrará os dados e evidências usados.</p></div></div><div className="suggestions"><button>O que mais concentra minha carteira?</button><button>Quanto tenho por instituição?</button><button>Explique meu patrimônio em dólar</button></div><div className="chat-input"><Input placeholder="Pergunte sobre sua carteira..." disabled/><Button size="icon" disabled><Send/></Button></div><small>Em breve · nenhuma pergunta é enviada nesta versão.</small></DialogContent></Dialog></main>;
}
