"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Bell, Bot, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDollarSign, Download, ExternalLink, FileSpreadsheet, FileText, Gauge, Home, Menu, Newspaper, PieChart as PieIcon, Plus, RotateCcw, Send, Settings, ShieldAlert, ShieldCheck, Sparkles, Upload, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";

type Position = { id:number; assetName:string; ticker:string|null; institution:string; account:string; assetClass:string; currency:string; quantity:number; unitPriceBrl:number; marketValueBrl:number; confidence:number };
type Batch = { id:number; fileName:string; status:string; rowCount:number; rejectedCount:number; createdAt:string; fxUsdBrl:number; fxSource:string; fxReferenceDate:string|null };
type Snapshot = { id:number; asOf:string; totalBrl:number; totalUsd:number; quality:string };
type Income = { id:number; type:string; ticker:string|null; assetName:string; amount:number; currency:string; paymentDate:string; source:string };
type Thesis = { id:number; ticker:string|null; assetName:string; objective:string; horizon:string; buyReason:string; increaseCriteria:string; reduceCriteria:string; exitCriteria:string; mainRisk:string; status:string };
type Rule = { dimension:string; thresholdPercent:number; enabled:boolean };
type Summary = {
  empty:boolean; totalBrl:number; totalUsd:number; fxUsdBrl?:number; fxSource?:string; fxReferenceDate?:string;
  institutions:number; allocation:{name:string;value:number}[]; institutionAllocation:{name:string;value:number}[]; positions:Position[];
  batch?:Batch; imports:Batch[]; snapshots:Snapshot[]; incomes:Income[]; theses:Thesis[]; rules:Rule[];
  workspace?:{name:string;baseCurrency:string;fxMode:string}; user?:{displayName:string;email:string;role:string};
};
type Tab = "Visão geral"|"Minha carteira"|"Importações"|"Performance"|"Rendimentos"|"Concentração"|"Minha tese"|"Relatórios"|"Notícias"|"Configurações";
type NewsItem = { title:string;url:string;source:string;publishedAt:string;category:string };

const colors=["#0d6b5d","#47a993","#ff8f70","#6672a8","#d7d0cb","#ffb000"];
const menu:[React.ElementType,Tab][]=[[Home,"Visão geral"],[WalletCards,"Minha carteira"],[Upload,"Importações"],[Gauge,"Performance"],[CircleDollarSign,"Rendimentos"],[PieIcon,"Concentração"],[ShieldCheck,"Minha tese"],[FileSpreadsheet,"Relatórios"],[Newspaper,"Notícias"],[Settings,"Configurações"]];
const emptySummary:Summary={empty:true,totalBrl:0,totalUsd:0,institutions:0,allocation:[],institutionAllocation:[],positions:[],imports:[],snapshots:[],incomes:[],theses:[],rules:[]};
const money=(value:number,currency:"BRL"|"USD")=>new Intl.NumberFormat("pt-BR",{style:"currency",currency,maximumFractionDigits:2}).format(value||0);
const date=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeZone:"America/Sao_Paulo"}).format(new Date(value));
const pct=(value:number,total:number)=>total?value/total*100:0;

function Logo(){return <div className="brand"><span className="brand-mark"><i/><i/><i/></span><span>Evidaris</span></div>}
function PageTitle({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="page-title"><div><h2>{title}</h2><p>{description}</p></div>{action}</div>}
function EmptyState({icon:Icon,title,description,action}:{icon:React.ElementType;title:string;description:string;action?:React.ReactNode}){return <div className="empty large"><Icon/><h3>{title}</h3><p>{description}</p>{action}</div>}

export default function Dashboard(){
  const router=useRouter();
  const [summary,setSummary]=useState<Summary>(emptySummary);
  const [active,setActive]=useState<Tab>("Visão geral");
  const [currency,setCurrency]=useState<"BRL"|"USD">("BRL");
  const [importOpen,setImportOpen]=useState(false),[aiOpen,setAiOpen]=useState(false),[thesisOpen,setThesisOpen]=useState(false);
  const [selectedAsset,setSelectedAsset]=useState<Position|null>(null);
  const [file,setFile]=useState<File|null>(null),[fxRate,setFxRate]=useState(""),[fxOverride,setFxOverride]=useState(false),[fxWarning,setFxWarning]=useState("");
  const [loading,setLoading]=useState(false),[notice,setNotice]=useState("");
  const [news,setNews]=useState<NewsItem[]>([]),[newsProvider,setNewsProvider]=useState(""),[newsLoading,setNewsLoading]=useState(false),[newsError,setNewsError]=useState("");
  const inputRef=useRef<HTMLInputElement>(null);
  const fx=summary.fxUsdBrl||Number(fxRate)||1,shownTotal=currency==="BRL"?summary.totalBrl:summary.totalUsd;
  const display=(brl:number)=>money(currency==="BRL"?brl:brl/fx,currency);

  const refresh=useCallback(async()=>{const response=await fetch("/api/portfolio");if(response.status===401){router.push("/signin-with-chatgpt?return_to=/");return}if(response.ok){const data=await response.json();setSummary(data);setCurrency(data.workspace?.baseCurrency==="USD"?"USD":"BRL")}},[router]);
  const loadFx=useCallback(async()=>{try{const q=await fetch("/api/fx").then(r=>r.json());if(q.rate){setFxRate(String(q.rate).replace(".",","));setFxWarning(q.warning||"")}else{setFxWarning(q.error||"Cotação automática indisponível.");setFxOverride(true)}}catch{setFxWarning("Cotação automática indisponível.");setFxOverride(true)}},[]);
  const loadNews=useCallback(async()=>{setNewsLoading(true);setNewsError("");try{const data=await fetch("/api/news").then(r=>r.json());setNews(data.items||[]);setNewsProvider(data.provider||"");setNewsError(data.error||"")}catch{setNewsError("Não foi possível consultar as notícias.")}finally{setNewsLoading(false)}},[]);
  useEffect(()=>{queueMicrotask(()=>{void refresh();void loadFx()})},[refresh,loadFx]);
  useEffect(()=>{if(active==="Notícias")queueMicrotask(()=>void loadNews())},[active,loadNews]);

  const classAllocation=summary.allocation;
  const topAssets=useMemo(()=>summary.positions.slice().sort((a,b)=>b.marketValueBrl-a.marketValueBrl),[summary.positions]);
  const snapshots=summary.snapshots.map(row=>({date:new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short"}).format(new Date(row.asOf)),value:currency==="BRL"?row.totalBrl:row.totalUsd}));
  const incomeTotal=summary.incomes.reduce((sum,row)=>sum+(row.currency==="BRL"?row.amount:row.amount*fx),0);

  async function importFile(selected=file){if(!selected)return;setLoading(true);setNotice("");const form=new FormData();form.append("file",selected);form.append("fxUsdBrl",fxRate.replace(",","."));form.append("fxOverride",String(fxOverride));try{const response=await fetch("/api/portfolio",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"Não foi possível importar.");setSummary(result);setNotice(result.duplicate?"Arquivo já importado; nenhuma posição foi duplicada.":`${result.batch.rowCount} posições importadas.`);setFile(null)}catch(error){setNotice(error instanceof Error?error.message:"Falha ao importar")}finally{setLoading(false)}}
  function useExample(){const csv="Produto;Código de Negociação;Tipo de Produto;Instituição;Conta;Quantidade;Preço de Fechamento;Valor Atualizado\nPetrobras PN;PETR4;Ações;XP Investimentos;001;120;38,45;4614,00\nVanguard S&P 500 BDR;IVVB11;ETFs;BTG Pactual;002;42;366,70;15401,40\nFII Kinea Rendimentos;KNCR11;Fundo Imobiliário;XP Investimentos;001;85;103,25;8776,25\nTesouro IPCA+ 2035;;Tesouro Direto;Tesouro Direto;TD;1;5248,90;5248,90";const sample=new File([csv],"posicao-b3-exemplo.csv",{type:"text/csv"});setFile(sample);void importFile(sample)}
  async function rollback(batch:Batch){const impact=batch.status==="COMPLETED"?summary.positions.filter(p=>p.id).reduce((s,p)=>s+p.marketValueBrl,0):0;if(!confirm(`Desfazer ${batch.fileName}?\n\nImpacto estimado na posição atual: ${money(impact,"BRL")}. O arquivo original e o log de auditoria serão preservados.`))return;const response=await fetch(`/api/portfolio?id=${batch.id}`,{method:"DELETE"});const result=await response.json();if(response.ok){setSummary(result);setNotice(`${result.positions} posições removidas. Impacto: ${money(result.impactBrl,"BRL")}.`)}else setNotice(result.error)}
  async function addIncome(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const body=Object.fromEntries(form);const response=await fetch("/api/incomes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(response.ok){event.currentTarget.reset();await refresh();setNotice("Rendimento registrado.")}else setNotice(result.error)}
  async function addThesis(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const body=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/theses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(response.ok){setThesisOpen(false);await refresh();setNotice("Tese registrada.")}else setNotice(result.error)}
  async function saveSettings(){const response=await fetch("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({baseCurrency:currency,fxMode:fxOverride?"MANUAL":"PTAX_WITH_MANUAL_OVERRIDE"})});setNotice(response.ok?"Preferências salvas.":"Não foi possível salvar.")}

  function Overview(){return <div className="tab-content">
    <section className="hero-card"><div className="total-block"><span>Patrimônio total</span><strong>{money(shownTotal,currency)}</strong><small>≈ {money(currency==="BRL"?summary.totalUsd:summary.totalBrl,currency==="BRL"?"USD":"BRL")}</small><em>{summary.empty?"Aguardando primeira importação":`Atualizado por ${summary.batch?.fileName}`}</em></div><div className="trend"><div className="trend-head"><span>Evolução observada ({currency})</span><b>{snapshots.length} snapshots</b></div>{snapshots.length?<ResponsiveContainer width="100%" height={170}><AreaChart data={snapshots}><XAxis dataKey="date" axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(Number(v),currency)}/><Area type="monotone" dataKey="value" stroke="#0d6b5d" strokeWidth={2.5} fill="#dff3ed"/></AreaChart></ResponsiveContainer>:<EmptyState icon={Gauge} title="Histórico ainda não iniciado" description="Cada nova importação cria um snapshot auditável."/ >}</div></section>
    <section className="import-card"><div className="import-icon"><FileSpreadsheet/></div><div><span>Conciliação B3</span><h2>{summary.empty?"Traga seu patrimônio":"Carteira atualizada"}</h2><p>{summary.empty?"Importe o Excel de posições da Área do Investidor.":`${summary.batch?.rowCount} linhas reconhecidas · ${summary.batch?.rejectedCount||0} pendências`}</p></div><Button onClick={()=>setImportOpen(true)}><Plus/>Importar arquivo</Button></section>
    <section className="result-card"><div className="section-title"><div><h2>Resumo verificável</h2><p>Somente dados sustentados pelas importações registradas</p></div><span className="status-pill">{summary.empty?"Sem dados":"Posição atual"}</span></div><div className="metrics"><article><span>Valor de mercado</span><strong>{money(shownTotal,currency)}</strong><small>posição importada</small></article><article><span>Ativos</span><strong>{summary.positions.length}</strong><small>com evidência</small></article><article><span>Instituições</span><strong>{summary.institutions}</strong><small>consolidadas</small></article><article><span>PTAX utilizada</span><strong>R$ {fx.toFixed(4)}</strong><small>{summary.fxReferenceDate?date(summary.fxReferenceDate):"aguardando cotação"}</small></article></div></section>
    <section className="portfolio-card"><div className="section-title"><div><h2>Sua carteira</h2><p>Distribuição do patrimônio importado</p></div><button onClick={()=>setActive("Minha carteira")}>Ver ativos <ChevronRight/></button></div>{summary.empty?<EmptyState icon={Upload} title="Nenhuma posição importada" description="Teste a jornada com um arquivo demonstrativo." action={<Button variant="outline" onClick={useExample}>Usar exemplo</Button>}/>:<div className="portfolio-body"><div className="donut"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={classAllocation} dataKey="value" innerRadius={62} outerRadius={92}>{classAllocation.map((item,index)=><Cell key={item.name} fill={colors[index%colors.length]}/>)}</Pie><Tooltip formatter={v=>display(Number(v))}/></PieChart></ResponsiveContainer><div><strong>{money(shownTotal,currency)}</strong><span>Total</span></div></div><div className="allocation-list">{classAllocation.map((item,index)=><div className="allocation-row" key={item.name}><span className="dot" style={{background:colors[index%colors.length]}}/><span>{item.name}</span><strong>{pct(item.value,summary.totalBrl).toFixed(0)}%</strong><em>{display(item.value)}</em></div>)}</div><div className="top-assets"><strong>Maiores posições</strong>{topAssets.slice(0,3).map(p=><div key={p.id}><span>{p.ticker||p.assetName}</span><em>{display(p.marketValueBrl)}</em></div>)}</div></div>}</section>
    <section className="insight"><Sparkles/><div><strong>Insight da sua carteira</strong><p>{summary.empty?"Importe uma posição para gerar diagnósticos rastreáveis.":`${classAllocation[0]?.name} representa ${pct(classAllocation[0]?.value||0,summary.totalBrl).toFixed(1)}% do patrimônio.`}</p></div><button onClick={()=>setAiOpen(true)}>Perguntar à IA <ChevronRight/></button></section>
  </div>}

  function Portfolio(){return <div className="tab-content"><PageTitle title="Minha carteira" description="Posição consolidada; expanda um ativo para ver sua origem." action={<Button onClick={()=>setImportOpen(true)}><Plus/>Importar</Button>}/>{summary.empty?<EmptyState icon={WalletCards} title="Sua carteira aparecerá aqui" description="Importe um arquivo B3 para começar."/>:<section className="data-card"><div className="table-wrap"><table><thead><tr><th>Ativo</th><th>Classe</th><th>Instituição</th><th>Quantidade</th><th>Preço</th><th>Participação</th><th>Valor</th></tr></thead><tbody>{topAssets.map(p=><tr key={p.id} onClick={()=>setSelectedAsset(p)}><td><strong>{p.ticker||p.assetName}</strong><small>{p.assetName}</small></td><td>{p.assetClass}</td><td>{p.institution}</td><td>{p.quantity.toLocaleString("pt-BR")}</td><td>{money(p.unitPriceBrl,"BRL")}</td><td>{pct(p.marketValueBrl,summary.totalBrl).toFixed(1)}%</td><td><strong>{display(p.marketValueBrl)}</strong></td></tr>)}</tbody></table></div></section>}</div>}

  function Imports(){return <div className="tab-content"><PageTitle title="Importações" description="Histórico, qualidade, câmbio e rollback de cada carga." action={<Button onClick={()=>setImportOpen(true)}><Plus/>Nova importação</Button>}/>{notice&&<p className="notice">{notice}</p>}<section className="cards-grid">{summary.imports.length?summary.imports.map(batch=><article className="data-card import-history" key={batch.id}><div><FileSpreadsheet/><span className={batch.status==="COMPLETED"?"success-badge":"muted-badge"}>{batch.status==="COMPLETED"?"Concluída":"Desfeita"}</span></div><h3>{batch.fileName}</h3><p>{date(batch.createdAt)} · {batch.rowCount} posições · {batch.rejectedCount} rejeitadas</p><small>Câmbio R$ {batch.fxUsdBrl.toFixed(4)} · {batch.fxSource}</small>{batch.status==="COMPLETED"&&<Button variant="outline" onClick={()=>void rollback(batch)}><RotateCcw/>Desfazer e ver impacto</Button>}</article>):<EmptyState icon={Upload} title="Nenhuma importação" description="Os lotes e suas evidências serão exibidos aqui."/>}</section></div>}

  function Performance(){const enough=snapshots.length>=2;return <div className="tab-content"><PageTitle title="Performance" description="Evolução observada por snapshots, sem reconstruir retornos inexistentes."/><section className="data-card performance-card">{enough?<><div className="metrics compact"><article><span>Primeiro snapshot</span><strong>{money(snapshots[0].value,currency)}</strong></article><article><span>Último snapshot</span><strong>{money(snapshots.at(-1)?.value||0,currency)}</strong></article><article><span>Variação patrimonial</span><strong>{money((snapshots.at(-1)?.value||0)-snapshots[0].value,currency)}</strong><small>inclui aportes e retiradas</small></article></div><ResponsiveContainer width="100%" height={330}><AreaChart data={snapshots}><XAxis dataKey="date"/><YAxis hide domain={["dataMin","dataMax"]}/><Tooltip formatter={v=>money(Number(v),currency)}/><Area type="monotone" dataKey="value" stroke="#0d6b5d" fill="#dff3ed" strokeWidth={3}/></AreaChart></ResponsiveContainer><p className="data-warning"><ShieldAlert/>TWR e XIRR permanecem indisponíveis até existirem movimentações e fluxos suficientes.</p></>:<EmptyState icon={Gauge} title="Histórico insuficiente" description="Importe a carteira em pelo menos duas datas. A variação inicial será patrimonial e não será apresentada como rentabilidade."/>}</section></div>}

  function Incomes(){return <div className="tab-content"><PageTitle title="Rendimentos" description="Dividendos, JCP, juros e cupons, separados da valorização."/><section className="split-grid"><form className="data-card form-card" onSubmit={addIncome}><h3>Registrar rendimento</h3><label>Ativo<Input name="assetName" required placeholder="Ex.: Petrobras PN"/></label><div className="form-row"><label>Ticker<Input name="ticker" placeholder="PETR4"/></label><label>Tipo<select name="type"><option>DIVIDEND</option><option>JCP</option><option>INTEREST</option><option>COUPON</option></select></label></div><div className="form-row"><label>Valor<Input name="amount" type="number" step="0.01" min="0.01" required/></label><label>Data<Input name="paymentDate" type="date" required/></label></div><input type="hidden" name="currency" value="BRL"/><Button type="submit">Salvar rendimento</Button></form><section className="data-card"><div className="metric-highlight"><span>Total registrado</span><strong>{display(incomeTotal)}</strong></div>{summary.incomes.length?<div className="item-list">{summary.incomes.map(row=><article key={row.id}><div><strong>{row.ticker||row.assetName}</strong><span>{row.type} · {date(row.paymentDate)} · {row.source}</span></div><b>{money(row.amount,row.currency as "BRL"|"USD")}</b></article>)}</div>:<EmptyState icon={CircleDollarSign} title="Sem rendimentos" description="Cadastre manualmente agora; importação de movimentações B3 entra pelo mesmo modelo."/>}</section></section></div>}

  function Concentration(){const rule=(d:string,f:number)=>summary.rules.find(r=>r.dimension===d)?.thresholdPercent||f;const alerts=[...topAssets.filter(p=>pct(p.marketValueBrl,summary.totalBrl)>rule("ASSET",20)).map(p=>({label:p.ticker||p.assetName,value:pct(p.marketValueBrl,summary.totalBrl),limit:rule("ASSET",20),type:"Ativo"})),...classAllocation.filter(i=>pct(i.value,summary.totalBrl)>rule("ASSET_CLASS",40)).map(i=>({label:i.name,value:pct(i.value,summary.totalBrl),limit:rule("ASSET_CLASS",40),type:"Classe"})),...summary.institutionAllocation.filter(i=>pct(i.value,summary.totalBrl)>rule("INSTITUTION",50)).map(i=>({label:i.name,value:pct(i.value,summary.totalBrl),limit:rule("INSTITUTION",50),type:"Instituição"}))];return <div className="tab-content"><PageTitle title="Concentração" description="Exposição por ativo, classe e instituição comparada aos limites definidos."/><section className="split-grid"><div className="data-card"><h3>Alertas atuais</h3>{alerts.length?<div className="alert-list">{alerts.map((a,i)=><article key={i}><ShieldAlert/><div><strong>{a.type}: {a.label}</strong><span>{a.value.toFixed(1)}% da carteira · limite {a.limit}%</span></div></article>)}</div>:<EmptyState icon={ShieldCheck} title="Nenhum limite excedido" description="As posições estão dentro das regras atuais."/>}</div><div className="data-card"><h3>Limites recomendados</h3><div className="rule-list">{[["Ativo",20],["Classe",40],["Instituição",50],["Moeda",70],["Emissor",25]].map(([name,value])=><div key={name}><span>{name}</span><Progress value={Number(value)}/><b>{value}%</b></div>)}</div></div></section></div>}

  function Theses(){return <div className="tab-content"><PageTitle title="Minha tese" description="O que precisa continuar verdadeiro para cada investimento permanecer na carteira." action={<Button onClick={()=>setThesisOpen(true)}><Plus/>Nova tese</Button>}/>{summary.theses.length?<section className="cards-grid">{summary.theses.map(t=><article className="data-card thesis-card" key={t.id}><div><ShieldCheck/><span className="success-badge">Ativa</span></div><h3>{t.ticker||t.assetName}</h3><p><strong>Objetivo:</strong> {t.objective}</p><p><strong>Horizonte:</strong> {t.horizon}</p><p><strong>Risco principal:</strong> {t.mainRisk}</p><details><summary>Ver critérios</summary><p><strong>Razão de compra:</strong> {t.buyReason}</p><p><strong>Aumentar:</strong> {t.increaseCriteria}</p><p><strong>Reduzir:</strong> {t.reduceCriteria}</p><p><strong>Sair:</strong> {t.exitCriteria}</p></details></article>)}</section>:<EmptyState icon={ShieldCheck} title="Nenhuma tese cadastrada" description="Registre a lógica da decisão antes que o mercado teste sua convicção." action={<Button onClick={()=>setThesisOpen(true)}>Criar primeira tese</Button>}/>}</div>}

  function Reports(){return <div className="tab-content"><PageTitle title="Relatórios" description="Demonstrativo da posição atual com origem, câmbio e aviso metodológico."/><section className="report-preview data-card"><div className="report-paper"><Logo/><span>RELATÓRIO PATRIMONIAL</span><h2>{summary.user?.displayName||"Titular da carteira"}</h2><div className="report-total"><small>Patrimônio consolidado</small><strong>{money(summary.totalBrl,"BRL")}</strong><em>{money(summary.totalUsd,"USD")}</em></div><div className="report-columns"><div><span>Ativos</span><b>{summary.positions.length}</b></div><div><span>Instituições</span><b>{summary.institutions}</b></div><div><span>PTAX</span><b>R$ {fx.toFixed(4)}</b></div></div><p>Posição demonstrativa baseada no último lote importado. Não constitui recomendação de investimento.</p></div><div className="report-actions"><h3>Baixar demonstrativo</h3><p>O PDF segue o modelo visual da Evidaris; o CSV preserva os dados para conferência.</p><Button disabled={summary.empty} onClick={()=>window.open("/api/reports?format=pdf","_self")}><FileText/>Baixar PDF</Button><Button variant="outline" disabled={summary.empty} onClick={()=>window.open("/api/reports?format=csv","_self")}><Download/>Baixar CSV</Button><small>Envio por e-mail: arquitetura preparada para Resend após domínio verificado.</small></div></section></div>}

  function News(){return <div className="tab-content"><PageTitle title="Notícias" description="Mercado brasileiro com links para as publicações originais da B3 e da CVM." action={<span className="status-pill">{newsProvider||"Atualizando"}</span>}/>{newsLoading?<EmptyState icon={Newspaper} title="Buscando notícias" description="Consultando fontes atuais..."/>:news.length?<section className="news-grid">{news.map((item,i)=><a className="data-card news-card" href={item.url} target="_blank" rel="noreferrer" key={i}><span>{item.category}</span><h3>{item.title}</h3><p>{item.source} · {date(item.publishedAt)}</p><ExternalLink/></a>)}</section>:<EmptyState icon={Newspaper} title="Notícias temporariamente indisponíveis" description={newsError||"As fontes não retornaram publicações."} action={<Button variant="outline" onClick={()=>void loadNews()}>Tentar novamente</Button>}/>}</div>}

  function Configuration(){return <div className="tab-content"><PageTitle title="Configurações" description="Preferências do workspace, privacidade e dados."/><section className="split-grid"><div className="data-card form-card"><h3>Moeda e câmbio</h3><label>Moeda da visão geral<select value={currency} onChange={e=>setCurrency(e.target.value as "BRL"|"USD")}><option>BRL</option><option>USD</option></select></label><label className="check-row"><input type="checkbox" checked={!fxOverride} onChange={e=>setFxOverride(!e.target.checked)}/><span><strong>PTAX automática</strong><small>Usa o último fechamento do Banco Central; permite contingência manual.</small></span></label><Button onClick={saveSettings}>Salvar preferências</Button></div><div className="data-card privacy-card"><ShieldCheck/><h3>Privacidade e segurança</h3><ul><li>Dados separados por workspace</li><li>Credenciais não são armazenadas no banco da Evidaris</li><li>Importações e rollbacks possuem auditoria</li><li>Originais mantidos por três meses</li><li>Exportação PDF e CSV registrada</li></ul><Button variant="outline" disabled>Baixar meus dados — próxima versão</Button></div></section></div>}

  const pages:Record<Tab,()=>React.ReactNode>={"Visão geral":Overview,"Minha carteira":Portfolio,"Importações":Imports,"Performance":Performance,"Rendimentos":Incomes,"Concentração":Concentration,"Minha tese":Theses,"Relatórios":Reports,"Notícias":News,"Configurações":Configuration};
  const Current=pages[active];
  return <main className="app-shell"><aside className="sidebar"><Logo/><nav>{menu.map(([Icon,label])=><button className={active===label?"active":""} key={label} onClick={()=>setActive(label)}><Icon/>{label}</button>)}</nav><div className="verified"><ShieldCheck/><strong>Carteira verificada</strong><span>{summary.empty?"Nenhum arquivo conciliado":`${summary.institutions} instituições · ${summary.positions.length} ativos`}</span><Progress value={summary.empty?0:100}/><small>{summary.empty?"Importe seu arquivo B3":"100% das posições lidas"}</small></div></aside>
  <section className="workspace"><header><button className="mobile-menu"><Menu/></button><div><h1>{active}</h1><p>Clareza que você pode conferir.</p></div><div className="header-actions"><select value={currency} onChange={e=>setCurrency(e.target.value as "BRL"|"USD")}><option>BRL</option><option>USD</option></select><button><Bell/></button><span className="avatar">{(summary.user?.displayName||"GM").split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</span></div></header><div className="content-grid"><Current/></div></section>
  <button className="ai-fab" onClick={()=>setAiOpen(true)}><Bot/><span>Pergunte à Evidaris</span></button><nav className="mobile-nav"><button className={active==="Visão geral"?"active":""} onClick={()=>setActive("Visão geral")}><Home/>Início</button><button className={active==="Minha carteira"?"active":""} onClick={()=>setActive("Minha carteira")}><BriefcaseBusiness/>Carteira</button><button onClick={()=>setImportOpen(true)} className="import"><Plus/></button><button className={active==="Relatórios"?"active":""} onClick={()=>setActive("Relatórios")}><FileSpreadsheet/>Relatórios</button><button onClick={()=>setAiOpen(true)}><Bot/>IA</button></nav>
  <Dialog open={importOpen} onOpenChange={setImportOpen}><DialogContent className="import-dialog"><DialogHeader><DialogTitle>Importar posição da B3</DialogTitle><DialogDescription>Excel ou CSV da Área do Investidor. A PTAX é preenchida automaticamente.</DialogDescription></DialogHeader><div className="steps"><span className="done"><CheckCircle2/>Arquivo</span><i/><span>Validar</span><i/><span>Consolidar</span></div><button className="dropzone" onClick={()=>inputRef.current?.click()}><Upload/><strong>{file?file.name:"Selecione seu arquivo"}</strong><span>O original fica como evidência por três meses.</span></button><input ref={inputRef} hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/>{fxWarning&&<p className="data-warning"><ShieldAlert/>{fxWarning}</p>}<label className="check-row"><input type="checkbox" checked={fxOverride} onChange={e=>setFxOverride(e.target.checked)}/><span><strong>Substituir PTAX manualmente</strong><small>A alteração ficará registrada no lote.</small></span></label><label className="fx-field">USD/BRL de contingência<Input value={fxRate} onChange={e=>setFxRate(e.target.value)} inputMode="decimal" disabled={!fxOverride&&!fxWarning}/></label>{notice&&<p className="notice">{notice}</p>}<div className="dialog-actions"><Button variant="outline" onClick={useExample}>Usar exemplo</Button><Button onClick={()=>void importFile()} disabled={!file||loading||!Number(fxRate.replace(",","."))}>{loading?"Conciliando...":"Validar e importar"}</Button></div></DialogContent></Dialog>
  <Dialog open={Boolean(selectedAsset)} onOpenChange={()=>setSelectedAsset(null)}><DialogContent>{selectedAsset&&<><DialogHeader><DialogTitle>{selectedAsset.ticker||selectedAsset.assetName}</DialogTitle><DialogDescription>{selectedAsset.assetName}</DialogDescription></DialogHeader><div className="asset-detail"><div><span>Valor</span><strong>{display(selectedAsset.marketValueBrl)}</strong></div><div><span>Participação</span><strong>{pct(selectedAsset.marketValueBrl,summary.totalBrl).toFixed(2)}%</strong></div><dl><dt>Classe</dt><dd>{selectedAsset.assetClass}</dd><dt>Instituição</dt><dd>{selectedAsset.institution}</dd><dt>Conta</dt><dd>{selectedAsset.account}</dd><dt>Quantidade</dt><dd>{selectedAsset.quantity.toLocaleString("pt-BR")}</dd><dt>Preço unitário</dt><dd>{money(selectedAsset.unitPriceBrl,"BRL")}</dd><dt>Confiança</dt><dd>{(selectedAsset.confidence*100).toFixed(0)}%</dd></dl><Button onClick={()=>{setSelectedAsset(null);setActive("Minha tese");setThesisOpen(true)}}>Registrar tese deste ativo</Button></div></>}</DialogContent></Dialog>
  <Dialog open={thesisOpen} onOpenChange={setThesisOpen}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>Nova tese de investimento</DialogTitle><DialogDescription>Registre critérios observáveis; não é uma recomendação da plataforma.</DialogDescription></DialogHeader><form className="thesis-form" onSubmit={addThesis}><div className="form-row"><label>Ativo<Input name="assetName" defaultValue={selectedAsset?.assetName} required/></label><label>Ticker<Input name="ticker" defaultValue={selectedAsset?.ticker||""}/></label><label>Horizonte<Input name="horizon" placeholder="Ex.: 5 anos" required/></label></div><label>Objetivo<textarea name="objective" required/></label><label>Razão de compra<textarea name="buyReason" required/></label><div className="form-row"><label>Quando aumentar<textarea name="increaseCriteria" required/></label><label>Quando reduzir<textarea name="reduceCriteria" required/></label></div><label>Quando sair<textarea name="exitCriteria" required/></label><label>Risco principal<textarea name="mainRisk" required/></label><Button type="submit">Salvar tese</Button></form></DialogContent></Dialog>
  <Dialog open={aiOpen} onOpenChange={setAiOpen}><DialogContent className="ai-dialog"><DialogHeader><div className="ai-title"><span><Sparkles/></span><div><DialogTitle>Assistente Evidaris</DialogTitle><DialogDescription>Simulação segura · nenhuma pergunta é enviada ainda</DialogDescription></div></div></DialogHeader><div className="ai-welcome"><Bot/><div><strong>Como posso ajudar?</strong><p>Quando conectado, cada resposta mostrará dados, fontes e incerteza.</p></div></div><div className="suggestions"><button>O que concentra minha carteira?</button><button>Quanto tenho por instituição?</button><button>Explique a PTAX utilizada</button></div><div className="chat-input"><Input disabled placeholder="Pergunte sobre sua carteira..."/><Button size="icon" disabled><Send/></Button></div></DialogContent></Dialog></main>;
}
